baseURL = "/"
languageCode = "en-IE"
title = "Aideen Fay"

theme = "hello-friend"

[params]
  defaultTheme = "light"
  showReadingTime = false

  # You can use Markdown for urls [text](//domain.tld/source)
  #
  # All icons using Fontawesom's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons.

  # To provide more meta data for search engings feel free to add a few informations.
  # This lines will be inserted as meta tags.
  name = "Aideen Fay"
  description = "Engineer, Programmer, Runner and Student"

  # For a static site it's not possible to provide a contact form. The contact form uses
  # www.formspree.io as a proxy. The form makes a Post request to their servers to send an email
  # Visitors can send up to a 1000 emails each month
  #
  # How to setup formspree
  #
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email to yourself to confirm your account
  # - click the confirmation link in the email from www.formspree.io
  # - That's all. Enjoy mailing!
  email = "me@aideen.dev"
  
  [languages]
    [languages.en]
    title = "Aideen Fay"
    subtitle = "My personal blog"
    keywords = ""
    copyright = "Copyright © Aideen Fay"
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Keep reading"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer"
    olderPosts = "Older"
    minuteReadingTime = "minutes to read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "Aideen Fay"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About me"
        url = "/about"

      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/"